/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary": "#9d422b",
        "surface-container": "#f0eee9",
        "on-surface-variant": "#44474d",
        "surface-container-lowest": "#ffffff",
        "primary": "#031632",
        "tertiary-fixed": "#ffdcbe",
        "surface": "#fbf9f4",
        "on-tertiary-fixed-variant": "#6a3c00",
        "primary-fixed-dim": "#b6c7eb",
        "surface-bright": "#fbf9f4",
        "background": "#fbf9f4",
        "surface-container-low": "#f5f3ee",
        "secondary-fixed-dim": "#ffb4a2",
        "on-secondary-fixed-variant": "#7e2b16",
        "on-tertiary-fixed": "#2d1600",
        "surface-dim": "#dbdad5",
        "error": "#ba1a1a",
        "surface-container-highest": "#e4e2dd",
        "surface-variant": "#e4e2dd",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#374765",
        "on-tertiary-container": "#cc822f",
        "on-secondary-container": "#74240f",
        "on-primary": "#ffffff",
        "surface-tint": "#4e5f7e",
        "on-primary-fixed": "#081b38",
        "outline-variant": "#c5c6ce",
        "on-background": "#1b1c19",
        "on-error-container": "#93000a",
        "outline": "#75777e",
        "primary-fixed": "#d7e2ff",
        "primary-container": "#1a2b48",
        "tertiary-fixed-dim": "#ffb871",
        "inverse-surface": "#30312e",
        "on-surface": "#1b1c19",
        "secondary-fixed": "#ffdbd2",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "tertiary": "#261200",
        "inverse-on-surface": "#f2f1ec",
        "on-error": "#ffffff",
        "secondary-container": "#fd8c6f",
        "on-primary-container": "#8293b5",
        "inverse-primary": "#b6c7eb",
        "tertiary-container": "#432400",
        "on-secondary-fixed": "#3c0800",
        "surface-container-high": "#eae8e3"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px"
      },
      spacing: {
        "margin-desktop": "64px",
        "container-max": "1440px",
        "gutter": "32px",
        "unit": "8px",
        "margin-mobile": "24px"
      },
      fontFamily: {
        "display-lg": ["EB Garamond", "serif"],
        "headline-lg": ["EB Garamond", "serif"],
        "headline-lg-mobile": ["EB Garamond", "serif"],
        "headline-md": ["EB Garamond", "serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-caps": ["Plus Jakarta Sans", "sans-serif"],
        "button": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["72px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "500" }],
        "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "500" }],
        "headline-lg-mobile": ["36px", { lineHeight: "1.2", fontWeight: "500" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" }],
        "button": ["14px", { lineHeight: "1.0", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
};
